[project]
name = "lasr-analysing-faithfulness-of-reasoning-to-internal-concepts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch",
    "huggingface-hub",
    "safetensors",
    "requests",
    "ipython",
]

[tool.setuptools.packages.find]
include = ["src*"]
